### ISSUE TITLE
Attempt to use UCP endpoints after closing in distributed

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [rapidsai/ucx-py#156]
I used dask and distributed master branches. Do you see an issue here?

```
$ python3 benchmarks/old_tests/dask-dot-prod.py --protocol ucx --server A.B.C.D --port 13337
distributed.comm.ucx - DEBUG - UCXConnector.connect: A.B.C.D:13337
distributed.comm.ucx - DEBUG - UCX.__init__ <UCX  local=None remote=ucx://A.B.C.D:13337>
distributed.comm.ucx - DEBUG - UCXConnector.connect: A.B.C.D:13337
distributed.comm.ucx - DEBUG - UCX.__init__ <UCX  local=None remote=ucx://A.B.C.D:13337>
Connected to <Client: scheduler='ucx://A.B.C.D:13337' processes=1 cores=1>
8.00 GB
dask.array<sum-aggregate, shape=(1000, 1000), dtype=float64, chunksize=(1000,
1000), chunktype=numpy.ndarray>
        Took 36.65s
distributed.comm.ucx - DEBUG - Destroyed UCX endpoint
distributed.comm.ucx - DEBUG - Destroyed UCX endpoint
distributed.utils - ERROR -
Traceback (most recent call last):
  File "distributed/utils.py", line 657, in
log_errors
    yield
  File "distributed/comm/ucx.py", line 124,
in read
    resp = await self.ep.recv_future()
concurrent.futures._base.CancelledError
```

**Comment by quasiben** [comment]
Yes and no.  The issue here common to what I see -- but I don't think it is yielding incorrect results.  Still, it is a problem and I think this goes back to how dask does not cleanly stop UCP when shutting down

**Comment by quasiben** [comment]
With new binding in I believe we can close this
