### ISSUE TITLE
Scheduler Hang and Segfault

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#167]
# Configuration

## Scheduler
```
export SCHEDULER=1
export UCX_RNDV_SCHEME=put_zcopy
export UCX_MEMTYPE_CACHE=n
export UCX_TLS=rc,cuda_copy,cuda_ipc
export CUDA_VISIBLE_DEVICES=0,1,2,3
gdb --args python /home/nfs/bzaitlen/miniconda3/envs/cudf-dev/bin/dask-scheduler --interface ib0 --protocol ucx
```

## Workers

Four workers with the following startup

> UCX_RNDV_SCHEME=put_zcopy UCX_MEMTYPE_CACHE=n UCX_TLS=rc,cuda_copy,cuda_ipc CUDA_VISIBLE_DEVICES=0,1,2,3 dask-worker ucx://10.33.225.165:8786 --nthreads=1 --memory-limit 32gb --no-nanny --protocol=ucx

each worker cycles through the starting value for `CUDA_VISIBLE_DEVICES`

Joining two large dask_cudf dataframes results in a hang in all the workers and eventually the scheduler segfaults (see backtrace below).  I am also printing out (every second) what the python thread is doing.  For a number of minutes the logs show:

```

        self._context.run(self._callback, *self._args)
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/comm/ucx.py", line 185, in connect
        ep = await ucp.get_endpoint(ip.encode(), port)
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/asyncio/base_events.py", line 398, in create_task
        def create_task(self, coro):
```

This could be an artifact of a worker locked up and the scheduler trying to reconnect

## Backtrace

```
width': 86526109.0620687}, 'reply': True}
distributed.core - DEBUG - Calling into handler heartbeat_worker
distributed.core - DEBUG - Message from 'ucx://10.33.225.165:8786': {'op': 'heartbeat_worker', 'address': 'ucx://10.33.225.165:36725', 'now': 1566938571.8552446, 'metrics': {'gpu': {'utilization': (0, 0, 0, 0, 0, 0, 0, 0), 'memory-used': (10827137024, 8239251456, 18506907
648, 20314652672, 555286528, 12124160, 12124160, 12124160)}, 'cpu': 0.0, 'memory': 8786096128, 'time': 1566938571.8547459, 'read_bytes': 588794.826710772, 'write_bytes': 595846.0819864963, 'num_fds': 114, 'executing': 0, 'in_memory': 272, 'ready': 0, 'in_flight': 0, 'band
width': 88910595.25949559}, 'reply': True}
distributed.core - DEBUG - Calling into handler heartbeat_worker
distributed.comm.ucx - DEBUG - UCXConnector.connect: 10.33.225.165:49812

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffdc9dc595 in uct_rdmacm_iface_process_event (iface=0x55555704b720, event=0x5555584ef140) at ../../../../../src/uct/ib/rdmacm/rdmacm_iface.c:384
384             hdr = *(uct_rdmacm_priv_data_hdr_t *)event->param.conn.private_data;
(gdb) bt
#0  0x00007fffdc9dc595 in uct_rdmacm_iface_process_event (iface=0x55555704b720, event=0x5555584ef140)
    at ../../../../../src/uct/ib/rdmacm/rdmacm_iface.c:384
#1  0x00007fffdc9dc89a in uct_rdmacm_iface_event_handler (fd=65, arg=0x55555704b720)
    at ../../../../../src/uct/ib/rdmacm/rdmacm_iface.c:440
#2  0x00007ffff414c4d7 in __ucs_async_poll_missed (async=0x555556c6a028) at ../../../src/ucs/async/async.c:579
#3  0x00007ffff47eee14 in ucs_async_check_miss (async=0x555556c6a028)
    at /home/nfs/bzaitlen/GitRepos/ucx/build/../src/ucs/async/async.h:80
#4  0x00007ffff47f4209 in ucp_worker_progress (worker=0x555556c6a020) at ../../../src/ucp/core/ucp_worker.c:1645
#5  0x00007ffff4b3d0dc in ucp_ipy_worker_progress (ucp_worker=0x555556c6a020) at ucp/_libs/src/ucp_py_ucp_fxns.c:191
#6  0x00007ffff4b3d8e0 in ucp_py_get_ep (ip=ip@entry=0x7fffbc0e2110 "10.33.225.165", listener_port=49812)
    at ucp/_libs/src/ucp_py_ucp_fxns.c:656
#7  0x00007ffff4ac3400 in __pyx_pf_6ucp_py_8Endpoint_4connect (__pyx_v_self=0x7fffbec23730, __pyx_v_port=<optimized out>,
    __pyx_v_ip=<optimized out>) at ucp/_libs/ucp_py.c:18060
#8  __pyx_pw_6ucp_py_8Endpoint_5connect (__pyx_v_self=0x7fffbec23730, __pyx_args=<optimized out>, __pyx_kwds=<optimized out>)
    at ucp/_libs/ucp_py.c:18036
```

**Comment by quasiben** [comment]
I can no longer reproduce this error. Still the setup may prove useful should someone else need a similar debugging setup
