### ISSUE TITLE
High CPU usage when using with Dask

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#242]
I'm running the following script on a commodity linux laptop without a GPU, just to verify that things work

```python
from dask.distributed import Client
import asyncio

async def f():
    async with Client(protocol="ucx", asynchronous=True, n_workers=4, processes=False) as c:
        await asyncio.sleep(10)

asyncio.get_event_loop().run_until_complete(f())
```

When I set `UCX_TLS=tcp` then I get the following error:

```python-traceback
[1570820720.745880] [carbon:18701:0]   ucp_listener.c:431  UCX  ERROR none of the available transports can listen for connections on 0.0.0.0:41789
Traceback (most recent call last):
  File "foo.py", line 8, in <module>
    asyncio.get_event_loop().run_until_complete(f())
  File "/home/mrocklin/miniconda3/envs/ucx/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "foo.py", line 5, in f
    async with Client(protocol="ucx", asynchronous=True, n_workers=4, processes=False) as c:
  File "/home/mrocklin/workspace/distributed/distributed/client.py", line 1103, in __aenter__
    await self._started
  File "/home/mrocklin/workspace/distributed/distributed/client.py", line 952, in _start
    **self._startup_kwargs
  File "/home/mrocklin/workspace/distributed/distributed/deploy/spec.py", line 346, in _
    await self._start()
  File "/home/mrocklin/workspace/distributed/distributed/deploy/spec.py", line 268, in _start
    self.scheduler = await self.scheduler
  File "/home/mrocklin/workspace/distributed/distributed/scheduler.py", line 1214, in start
    self.listen(self._start_address, listen_args=self.listen_args)
  File "/home/mrocklin/workspace/distributed/distributed/core.py", line 313, in listen
    self.listener.start()
  File "/home/mrocklin/workspace/distributed/distributed/comm/ucx.py", line 259, in start
    self.ucp_server = ucp.create_listener(serve_forever, port=self._input_port)
  File "/home/mrocklin/miniconda3/envs/ucx/lib/python3.7/site-packages/ucp/public_api.py", line 48, in create_listener
    return _get_ctx().create_listener(callback_func, port)
  File "ucp/_libs/core.pyx", line 243, in ucp._libs.core.ApplicationContext.create_listener
  File "ucp/_libs/core.pyx", line 20, in ucp._libs.core.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
```

When I add in `sm`, which I think is shared memory, things connect, but start to pin a CPU

cc @madsbk @Akshay-Venkatesh

**Comment by mrocklin** [comment]
Possibly related.  This hangs:

```python
In [1]: from dask.distributed import Client                                                                        
/home/mrocklin/workspace/ucx-py/ucp/__init__.py:20: UCXWarning: Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX
  "Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX", UCXWarning
c[1570826086.310179] [carbon:13081:0]         parser.c:1568 UCX  WARN  unused env variable: UCX_PATH (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
l
In [2]: client = Client(protocol="ucx", processes=False, n_workers=4, host="127.0.0.1")                            

In [3]:                                                                                                            
Do you really want to exit ([y]/n)? 
[1570826102.646686] [carbon:13081:1]      sockcm_ep.c:114  UCX  ERROR failed to connect to 127.0.0.1:48149
```

**Comment by pentschev** [comment]
This is really old, and configurations are now hidden in the Distributed layer, so the users don't have to specify `UCX_TLS` manually, and instead rely on the Dask config via the `distributed.comm.ucx` namespace. Closing.
