### ISSUE TITLE
[BUG] Creating a dask-cuda cluster using UCX protocol fails

### ISSUE THREAD

**Issue by randerzander** [rapidsai/ucx-py#286]
Using `jakirkham/label/ucx-new` packages and `dask-cuda` installed from master with `dask` and `distributed` 2.6:
```
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait

cluster = LocalCUDACluster(protocol="ucx")
```

Notebook level trace:
```
/conda/envs/rapids/lib/python3.7/site-packages/ucp/__init__.py:16: UCXWarning: Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX
  "Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX", UCXWarning
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - WARNING - Restarting worker
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - ERROR - Failed to restart worker after its process exited
Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 389, in _on_exit
    await self.instantiate()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 328, in instantiate
    result = await self.process.start()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 508, in start
    msg = await self._wait_until_connected(uid)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 622, in _wait_until_connected
    raise msg
TypeError: exceptions must derive from BaseException
distributed.nanny - WARNING - Restarting worker
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - ERROR - Failed to restart worker after its process exited
Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 389, in _on_exit
    await self.instantiate()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 328, in instantiate
    result = await self.process.start()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 508, in start
    msg = await self._wait_until_connected(uid)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 622, in _wait_until_connected
    raise msg
TypeError: exceptions must derive from BaseException
distributed.nanny - WARNING - Restarting worker
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - ERROR - Failed to restart worker after its process exited
Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 389, in _on_exit
    await self.instantiate()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 328, in instantiate
    result = await self.process.start()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 508, in start
    msg = await self._wait_until_connected(uid)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 622, in _wait_until_connected
    raise msg
TypeError: exceptions must derive from BaseException
distributed.nanny - WARNING - Restarting worker
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
```

Jupyter server log:
```
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 692, in run
    await worker
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1014, in start
    await self._register_with_scheduler()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 789, in _register_with_scheduler
    types = {k: typename(v) for k, v in self.data.items()}
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 789, in <dictcomp>
    types = {k: typename(v) for k, v in self.data.items()}
  File "/conda/envs/rapids/lib/python3.7/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask_cuda-0.10.0a1+9.g3f1a4f2-py3.7.egg/dask_cuda/device_host_file.py", line 154, in __getitem__
    return self.host_buffer[key]
  File "/conda/envs/rapids/lib/python3.7/site-packages/zict/buffer.py", line 70, in __getitem__                                               
    return self.slow_to_fast(key)
  File "/conda/envs/rapids/lib/python3.7/site-packages/zict/buffer.py", line 57, in slow_to_fast
    value = self.slow[key]
  File "/conda/envs/rapids/lib/python3.7/site-packages/zict/func.py", line 39, in __getitem__
    return self.load(self.d[key])
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 468, in deserialize_bytes
    return deserialize(header, frames)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize
    return loads(header, frames)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 62, in pickle_loads
    return pickle.loads(b"".join(frames))
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by jakirkham** [comment]
Did you pick one of [these sets of environment variables]( https://github.com/rapidsai/ucx-py#tcp-support ) and set them?

**Comment by randerzander** [comment]
Yes:
```
# ucx env var for plain TCP, no nvlink
ENV UCX_TLS=tcp,sockcm
ENV UCX_SOCKADDR_TLS_PRIORITY=sockcm
ENV UCXPY_IFNAME="eth0"
```

**Comment by jakirkham** [comment]
Are you able to run `client.get_versions(check=True)`?

**Comment by randerzander** [comment]
Unfortunately the cluster doesn't get created successfully, so I have no `client` object.

Editing the snippet to make that clearer.

**Comment by jakirkham** [comment]
Ah ok. Thanks for clarifying.

Does this crash your Python session as well? Also is this running in a script or some kind of REPL (IPython, Jupyter, etc.)?

**Comment by randerzander** [comment]
The same thing happens in Jupyter and when running from a script or from a plain Python prompt.

**Comment by jakirkham** [comment]
In a script, you would want to change this like so. Though IDK if that would fix the issue.

```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait

if __name__ == "__main__":
    cluster = LocalCUDACluster(protocol="ucx")
```

**Comment by pentschev** [comment]
The variables are not necessarily being passed correctly to the workers. Could you try the `DGX` class, as per my example in https://github.com/rapidsai/ucx-py/issues/284?

Despite the name, it _probably_ works in substitution to `LocalCUDACluster` for single-node, even if it's not a DGX.

**Comment by randerzander** [comment]
Using the new `conda-forge/label/rc_ucx` packages, I no longer get this error.
