### ISSUE TITLE
Install error "ucp/_libs/utils.c: No such file or directory"

### ISSUE THREAD

**Issue by aror92** [rapidsai/ucx-py#324]
I've installed UCX successfully via Spack and am trying to install ucx-py. I've been following the instructions here: https://ucx-py.readthedocs.io/en/latest/install.html. Though, because I've used Spack and not conda to install everything else, I have been trying to do it without the conda environment. On running `python setup.py build_ext --inplace`, I'm getting this error: `gcc: error: ucp/_libs/utils.c: No such file or directory`. Can anyone point me in the direction of what's going wrong and how to finish this installation? I'm working on an Intel Power9 cluster with Red Hat Enterprise Linux Server release 7.6 (Maipo). 

I have the following modules loaded:
```
Currently Loaded Modulefiles:
 1) py-setuptools-41.0.1-gcc-7.4.0-wyhql34   5) cuda-10.1.168-gcc-7.4.0-hzq4xoo  
 2) rdma-core-20-gcc-7.4.0-adbcrpv           6) ucx-1.6.0-gcc-7.4.0-h6e255u      
 3) numactl-2.0.12-gcc-7.4.0-55bhcx5         7) gcc-7.4.0-gcc-4.8.5-k5qa6mq      
 4) python-3.6.3-gcc-7.4.0-ziwbij6      
```    
(`rdma-core` and `numactl` contain the required libraries `libibverbs`, `librdmacm`, and `libnuma`)

Here is the complete build attempt and error message:
```
[ucx-py]$ python setup.py build_ext --inplace
running build_ext
building 'ucp._libs.utils' extension
/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/gcc-7.4.0-k5qa6mq3ud7ychs4h3pmiorukbrnwdav/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -fPIC -I/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/python-3.6.3-ziwbij6jb4zc3lmhbajok3i47lv5ohrs/include -I/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/python-3.6.3-ziwbij6jb4zc3lmhbajok3i47lv5ohrs/include/python3.6m -c ucp/_libs/utils.c -o build/temp.linux-ppc64le-3.6/ucp/_libs/utils.o -std=c99
gcc: error: ucp/_libs/utils.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command '/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/gcc-7.4.0-k5qa6mq3ud7ychs4h3pmiorukbrnwdav/bin/gcc' failed with exit status 1
```

**Comment by madsbk** [comment]
Try to install using this command `pip install -v "git+https://github.com/rapidsai/ucx-py.git"`

**Comment by jakirkham** [comment]
Probably need to install Cython as well.

**Comment by quasiben** [comment]
Interesting!  I've never heard of spack.  Is this it: https://spack.readthedocs.io/en/latest/ ?  i also noticed that you are using `ucx-1.6.0` .  ucx-py is currently being built and tested against ucx 1.7.  Would it be possible to upgrade to latest in the v1.7.x branch

**Comment by aror92** [comment]
@madsbk Thanks. I just tried that and got the same `ucp/_libs/utils.c: No such file or directory` error.

```

[ucx-py]$ pip install -v "git+https://github.com/rapidsai/ucx-py.git"
Created temporary directory: /tmp/pip-ephem-wheel-cache-d5j16kgi
Created temporary directory: /tmp/pip-req-tracker-xok3eudq
Created requirements tracker '/tmp/pip-req-tracker-xok3eudq'
Created temporary directory: /tmp/pip-install-tf6bg3vk
Collecting git+https://github.com/rapidsai/ucx-py.git
  Created temporary directory: /tmp/pip-req-build-r1nlulh5
  Cloning https://github.com/rapidsai/ucx-py.git to /tmp/pip-req-build-r1nlulh5
  Running command git clone -q https://github.com/rapidsai/ucx-py.git /tmp/pip-req-build-r1nlulh5
  Added git+https://github.com/rapidsai/ucx-py.git to build tracker '/tmp/pip-req-tracker-xok3eudq'
    Running setup.py (path:/tmp/pip-req-build-r1nlulh5/setup.py) egg_info for package from git+https://github.com/rapidsai/ucx-py.git
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/ucxpy.egg-info
    writing pip-egg-info/ucxpy.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/ucxpy.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/ucxpy.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/ucxpy.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/ucxpy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/ucxpy.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-r1nlulh5 has version 0.2+8.g724cbd4, which satisfies requirement ucxpy==0.2+8.g724cbd4 from git+https://github.com/rapidsai/ucx-py.git
  Removed ucxpy==0.2+8.g724cbd4 from git+https://github.com/rapidsai/ucx-py.git from build tracker '/tmp/pip-req-tracker-xok3eudq'
Installing collected packages: ucxpy
  Created temporary directory: /tmp/pip-record-npgbybn4
  Running setup.py install for ucxpy ...     Running command /home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/python-3.6.3-ziwbij6jb4zc3lmhbajok3i47lv5ohrs/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-r1nlulh5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-npgbybn4/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-ppc64le-3.6
    creating build/lib.linux-ppc64le-3.6/ucp
    copying ucp/__init__.py -> build/lib.linux-ppc64le-3.6/ucp
    copying ucp/_version.py -> build/lib.linux-ppc64le-3.6/ucp
    copying ucp/exceptions.py -> build/lib.linux-ppc64le-3.6/ucp
    copying ucp/public_api.py -> build/lib.linux-ppc64le-3.6/ucp
    copying ucp/utils.py -> build/lib.linux-ppc64le-3.6/ucp
    UPDATING build/lib.linux-ppc64le-3.6/ucp/_version.py
    set build/lib.linux-ppc64le-3.6/ucp/_version.py to '0.2+8.g724cbd4'
    running build_ext
    building 'ucp._libs.utils' extension
    creating build/temp.linux-ppc64le-3.6
    creating build/temp.linux-ppc64le-3.6/ucp
    creating build/temp.linux-ppc64le-3.6/ucp/_libs
    creating build/temp.linux-ppc64le-3.6/ucp/_libs/src
    /home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/gcc-7.4.0-k5qa6mq3ud7ychs4h3pmiorukbrnwdav/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -fPIC -I/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/python-3.6.3-ziwbij6jb4zc3lmhbajok3i47lv5ohrs/include -I/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/python-3.6.3-ziwbij6jb4zc3lmhbajok3i47lv5ohrs/include/python3.6m -c ucp/_libs/utils.c -o build/temp.linux-ppc64le-3.6/ucp/_libs/utils.o -std=c99
    gcc: error: ucp/_libs/utils.c: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command '/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/gcc-7.4.0-k5qa6mq3ud7ychs4h3pmiorukbrnwdav/bin/gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-req-build-r1nlulh5
Removed build tracker '/tmp/pip-req-tracker-xok3eudq'
Command "/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/python-3.6.3-ziwbij6jb4zc3lmhbajok3i47lv5ohrs/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-r1nlulh5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-npgbybn4/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-r1nlulh5/
Exception information:
Traceback (most recent call last):
  File "/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/py-pip-19.0.3-gtwjy6kex5ua7a2wy5w25wssfzdjd5qs/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/py-pip-19.0.3-gtwjy6kex5ua7a2wy5w25wssfzdjd5qs/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/py-pip-19.0.3-gtwjy6kex5ua7a2wy5w25wssfzdjd5qs/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/py-pip-19.0.3-gtwjy6kex5ua7a2wy5w25wssfzdjd5qs/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/py-pip-19.0.3-gtwjy6kex5ua7a2wy5w25wssfzdjd5qs/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/aror/spack/opt/spack/linux-rhel7-ppc64le/gcc-7.4.0/python-3.6.3-ziwbij6jb4zc3lmhbajok3i47lv5ohrs/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-r1nlulh5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-npgbybn4/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-r1nlulh5/
```

**Comment by jakirkham** [comment]
@aror92, not sure if you caught it, but you need to install Cython as well. The C files are not shipped and will need to be generated.

**Comment by aror92** [comment]
@jakirkham Thanks. I'm installing that now.

**Comment by aror92** [comment]
Thanks so much to everyone for the help! The install just finished successfully. @jakirkham Installing Cython and then following the install instructions at https://ucx-py.readthedocs.io/en/latest/install.html worked.

**Comment by jakirkham** [comment]
Great! Glad you are up and running. 😄

Please let us know if you have any other issues. Am going to go ahead and close this as resolved.

**Comment by jakirkham** [comment]
Adding a note to our README. ( https://github.com/rapidsai/ucx-py/pull/325 )

**Comment by madsbk** [comment]
I am a bit confused, when installing through pip should pip automatically download and install dependencies such as cython? @jakirkham

**Comment by quasiben** [comment]
@madsbk current setup.py does not define a `setup_requires` .  Adding cython there has some issues: https://stackoverflow.com/questions/37471313/setup-requires-with-cython but I don't think pip support is something we talked about extensively

**Comment by jakirkham** [comment]
Ah sorry @madsbk meant to respond here yesterday, but I think this one slipped.

@quasiben's answer is accurate.

Would add `setup_requires` is somewhat frowned upon because of its odd behavior. The Python community has moved to `pyproject.toml` for these kinds of things (see [PEP 518]( https://www.python.org/dev/peps/pep-0518/ )). Though support for it was a bit rocky in tooling initially. That has probably improved, but I haven't looked into it recently. If you think it is worth investigating, can I ask you to open a new GitHub issue?
