### ISSUE TITLE
msgpack unpack received extra data - crashes worker

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#411]
Am seeing workers getting killed due to an issue parsing headers in `msgpack` when running the workflow in issue ( https://github.com/rapidsai/ucx-py/issues/402 ). The workers don't appear to come back either. If I had to guess, the problem is similar to issue ( https://github.com/rapidsai/rmm/issues/223 ) and a workaround like the one found in PR ( https://github.com/rapidsai/rmm/pull/224 ) would be sufficient.

Note: It's important that this is only applied to host buffers and not device ones. Attempting to fix the latter would likely crash the program.

```python
distributed.core - ERROR - unpack(b) received extra data.
Traceback (most recent call last):
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/core.py", line 412, in handle_comm
    result = await result
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/scheduler.py", line 1731, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/scheduler.py", line 2688, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/core.py", line 456, in handle_stream
    msgs = await comm.read()
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/comm/ucx.py", line 196, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/comm/utils.py", line 69, in from_frames
    res = _from_frames()
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/comm/utils.py", line 55, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/protocol/core.py", line 101, in loads
    msg = loads_msgpack(small_header, small_payload)
  File "/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/distributed/protocol/core.py", line 193, in loads_msgpack
    return msgpack.loads(payload, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 209, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
```

**Comment by jakirkham** [comment]
Just to provide some more context, this error could be reproduced with msgpack alone like so.

```python
In [1]: import msgpack                                                          

In [2]: b = msgpack.packb([0, 1, 2])                                            

In [3]: b                                                                       
Out[3]: b'\x93\x00\x01\x02'

In [4]: msgpack.unpackb(b)                                                      
Out[4]: [0, 1, 2]

In [5]: msgpack.unpackb(b + b"\x00")                                            
---------------------------------------------------------------------------
ExtraData                                 Traceback (most recent call last)
<ipython-input-5-fd00fdf15121> in <module>
----> 1 msgpack.unpackb(b + b"\x00")

msgpack/_unpacker.pyx in msgpack._cmsgpack.unpackb()

ExtraData: unpack(b) received extra data.
```

**Comment by quasiben** [comment]
I started issue https://github.com/rapidsai/ucx-py/issues/376 to track how ucx-py should be robust to failure.  I am reading this issue as something similar, correct ? The bug here is that the worker did not restart cleanly not the unpacking

**Comment by jakirkham** [comment]
Well there are 2 problems:

1. Workers are not restarting after having issues.
2. Malformed header data is showing up.

**Comment by pentschev** [comment]
> Workers are not restarting after having issues.

Interesting, I know it's a different situation but every time I get a UCX crash (e.g., segfault) the workers restart and eventually finish. I wonder if there's a distinction of why a worker would restart when it finishes due to an exception when compared to a segfault.

**Comment by jakirkham** [comment]
Probably the worker state gets fouled up somehow.

**Comment by jakirkham** [comment]
Hmm...issue ( https://github.com/dask/distributed/issues/282 ) seems similar. Though not sure how we would still be running into that given it is closed and the time elapsed.

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/rapidsai/ucx-py/pull/415 ) fixes this.
