### ISSUE TITLE
Non-blocking Socket error

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#480]
@pentschev recently noticed that when starting dask-cuda-workers with `python -X` we get a backtrace with

```
  File "/datasets/pentschev/miniconda3/envs/ucx-src-101-0.14.0b200408/lib/python3.7/site-packages/ucp/continuous_ucx_progress.py", line 88, in _fd_reader_callback
    self.asyncio_task = self.event_loop.create_task(self._arm_worker())
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/ucx-src-101-0.14.0b200408/lib/python3.7/site-packages/ucp/continuous_ucx_progress.py", line 106, in _arm_worker
    await self.event_loop.sock_recv(self.rsock, 1)
  File "/datasets/pentschev/miniconda3/envs/ucx-src-101-0.14.0b200408/lib/python3.7/asyncio/selector_events.py", line 355, in sock_recv
    raise ValueError("the socket must be non-blocking")
ValueError: the socket must be non-blocking
```

Writing `self.rsock.setblocking(0)` and `wsock.setblocking(0)` resolves the issue.  This is not something I would have expected as I didn't think we were creating non-blocking sockets anywhere.  @madsbk is there any danger of ucx-py filling up the Python socket buffer ?  

- [Setting Socket Buffer Size](https://stackoverflow.com/questions/30888397/how-to-set-send-buffer-size-for-sockets-in-python)

**Comment by madsbk** [comment]
Hmm, the only place in Python that create sockets is here: https://github.com/rapidsai/ucx-py/blob/cd2cc1d8d536377e4711f78d8623b267f1c3976f/ucp/continuous_ucx_progress.py#L65
Which is called once per asyncio event loop.

**Comment by quasiben** [comment]
It looks like asyncio expects this to be non-blocking:
https://docs.python.org/3/library/asyncio-eventloop.html#working-with-socket-objects-directly

> sock must be a non-blocking socket.
