### ISSUE TITLE
Invalid parameter exception when using UCX with LocalCUDACluster

### ISSUE THREAD

**Issue by beckernick** [rapidsai/ucx-py#542]
In the nightlies from 2020-06-08 9:20 AM EDT, I cannot spin up a LocalCUDACluster with UCX (`enable_nvink=True` nor `=False`). TCP cluster works fine. This is on a DGX-2
 

```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait
from dask.utils import parse_bytes


protocol = "ucx"
enable_nvlink = protocol == "ucx"

cluster = LocalCUDACluster(
    local_directory="/raid/nicholasb/",
    protocol=protocol,
    enable_nvlink=enable_nvlink,
)

client = Client(cluster)
client
Task exception was never retrieved
future: <Task finished coro=<_listener_handler() done, defined at /raid/nicholasb/miniconda3/envs/rapids-20200608-cuda102-0920/lib/python3.7/site-packages/ucp/core.py:142> exception=UCXError('Invalid parameter')>
Traceback (most recent call last):
  File "/raid/nicholasb/miniconda3/envs/rapids-20200608-cuda102-0920/lib/python3.7/site-packages/ucp/core.py", line 154, in _listener_handler
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 374, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 56, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Invalid parameter
...
... (repeatedly)
```

Environment (key packages):

```
conda list | grep "ucx\|rapids\|distributed\|dask"
# packages in environment at /raid/nicholasb/miniconda3/envs/rapids-20200608-cuda102-0920:
cudf                      0.15.0a200608   py37_g029005c_900    rapidsai-nightly
cuml                      0.15.0a200608   cuda10.2_py37_ga58244d_386    rapidsai-nightly
dask                      2.18.0                     py_0    conda-forge
dask-core                 2.18.0                     py_0    conda-forge
dask-cuda                 0.15.0a200602           py37_12    rapidsai-nightly
dask-cudf                 0.15.0a200608   py37_g029005c_900    rapidsai-nightly
distributed               2.18.0+3.gd77e4c0f          pypi_0    pypi
libcudf                   0.15.0a200608   cuda10.2_g029005c_900    rapidsai-nightly
libcuml                   0.15.0a200608   cuda10.2_ga58244d_386    rapidsai-nightly
libcumlprims              0.15.0a200608       cuda10.2_39    rapidsai-nightly
librmm                    0.15.0a200608   cuda10.2_g3fab1b8_140    rapidsai-nightly
rmm                       0.15.0a200608   py37_g3fab1b8_140    rapidsai-nightly
ucx                       1.8.0+gf6ec8d4      cuda10.2_20    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.15.0a200608+gf6ec8d4         py37_61    rapidsai-nightly
```

Full Env:
```
conda list
# packages in environment at /raid/nicholasb/miniconda3/envs/rapids-20200608-cuda102-0920:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
aiohttp                   3.6.2                    pypi_0    pypi
arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
async-timeout             3.0.1                    pypi_0    pypi
asyncssh                  2.1.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
bokeh                     2.0.1            py37hc8dfbb8_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1002    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
catalogue                 1.0.0                      py_0    conda-forge
certifi                   2020.4.5.2       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.4.1                      py_0    conda-forge
cryptography              2.9.2            py37hb09aad4_0    conda-forge
cudatoolkit               10.2.89              h6bb024c_0    nvidia
cudf                      0.15.0a200608   py37_g029005c_900    rapidsai-nightly
cudnn                     7.6.5                cuda10.2_0
cuml                      0.15.0a200608   cuda10.2_py37_ga58244d_386    rapidsai-nightly
cupy                      7.5.0            py37h940342b_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.3            py37h3340039_1    conda-forge
cython-blis               0.4.1            py37h8f50634_1    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.18.0                     py_0    conda-forge
dask-core                 2.18.0                     py_0    conda-forge
dask-cuda                 0.15.0a200602           py37_12    rapidsai-nightly
dask-cudf                 0.15.0a200608   py37_g029005c_900    rapidsai-nightly
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.18.0+3.gd77e4c0f          pypi_0    pypi
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_2    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
fastavro                  0.23.4           py37h8f50634_0    conda-forge
fastrlock                 0.5              py37h3340039_0    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fsspec                    0.7.4                      py_0    conda-forge
gflags                    2.2.2             he1b5a44_1002    conda-forge
glog                      0.4.0                h49b9bf7_3    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
h5py                      2.10.0                   pypi_0    pypi
heapdict                  1.0.1                      py_0    conda-forge
httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.1            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.1                         0    conda-forge
ipykernel                 5.3.0            py37h43977f1_0    conda-forge
ipython                   7.15.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter-server-proxy      1.5.0                    pypi_0    pypi
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.1.4                      py_0    conda-forge
jupyterlab_server         1.1.5                      py_0    conda-forge
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.34                 h53a641e_4    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcudf                   0.15.0a200608   cuda10.2_g029005c_900    rapidsai-nightly
libcuml                   0.15.0a200608   cuda10.2_ga58244d_386    rapidsai-nightly
libcumlprims              0.15.0a200608       cuda10.2_39    rapidsai-nightly
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libhwloc                  2.1.0                h3c4fd83_0    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.15.0a200608   cuda10.2_g3fab1b8_140    rapidsai-nightly
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hfc65ed5_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
llvmlite                  0.32.0           py37h5202443_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
matplotlib                3.2.1                    pypi_0    pypi
mistune                   0.8.4           py37h8f50634_1001    conda-forge
monty                     3.0.2                    pypi_0    pypi
mpmath                    1.1.0                    pypi_0    pypi
msgpack-python            1.0.0            py37h99015e2_1    conda-forge
multidict                 4.7.6                    pypi_0    pypi
murmurhash                1.0.0            py37h3340039_0    conda-forge
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
nccl                      2.6.4.1              hc6a2c23_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                      pypi_0    pypi
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
numba                     0.49.1           py37h0da4684_0    conda-forge
numexpr                   2.7.1                    pypi_0    pypi
numpy                     1.17.5           py37h95a1406_0    conda-forge
oauth2client              4.1.3                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjdk                   8.0.192           h516909a_1005    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
palettable                3.3.0                    pypi_0    pypi
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.1.2            py37h718be6c_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
plac                      0.9.6                      py_1    conda-forge
plotly                    4.8.1                    pypi_0    pypi
preshed                   3.0.2            py37h3340039_2    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
psutil                    5.7.0            py37h8f50634_1    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py4j                      0.10.7                     py_1    conda-forge
pyarrow                   0.15.0           py37h8b68381_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pymatgen                  2020.4.29                pypi_0    pypi
pynvml                    8.0.4                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.16.0           py37h8f50634_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pyspark                   2.4.6                      py_0    conda-forge
python                    3.7.6           cpython_h8356626_6    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
pyzmq                     19.0.1           py37hac76be4_0    conda-forge
re2                       2020.04.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
retrying                  1.3.3                    pypi_0    pypi
rmm                       0.15.0a200608   py37_g3fab1b8_140    rapidsai-nightly
rsa                       4.0                        py_0    conda-forge
ruamel-yaml               0.16.10                  pypi_0    pypi
ruamel-yaml-clib          0.2.0                    pypi_0    pypi
scikit-learn              0.23.1           py37h8a51577_0    conda-forge
scipy                     1.4.1            py37ha3d9a3c_3    conda-forge
seaborn                   0.10.1                   pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
setuptools                47.1.1           py37hc8dfbb8_0    conda-forge
simpervisor               0.3                      pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_1    conda-forge
sortedcontainers          2.2.1              pyh9f0ad1d_0    conda-forge
spacy                     2.2.4            py37h99015e2_1    conda-forge
spdlog                    1.6.1                hc9558a2_0    conda-forge
spglib                    1.15.1                   pypi_0    pypi
sqlite                    3.30.1               hcee41ef_0    conda-forge
srsly                     1.0.2            py37h3340039_0    conda-forge
sympy                     1.6                      pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thinc                     7.4.0            py37h99015e2_2    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.46.1             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
ucx                       1.8.0+gf6ec8d4      cuda10.2_20    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.15.0a200608+gf6ec8d4         py37_61    rapidsai-nightly
uriparser                 0.9.3                he1b5a44_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wasabi                    0.6.0                      py_0    conda-forge
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.4.2                    pypi_0    pypi
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge
```

**Comment by pentschev** [comment]
This was introduced by https://github.com/rapidsai/ucx-py/pull/538, I'm checking it. I suggest using a version of UCX-Py from June 4th for now.

**Comment by beckernick** [comment]
cc @ayushdg for visibility

**Comment by quasiben** [comment]
@madsbk if you have time can you take a look at this issue ?

**Comment by pentschev** [comment]
I think https://github.com/rapidsai/ucx-py/pull/544 should fix this. On a DGX-2 I was able to reproduce the issue using the code from the description, with #544 it went away for me.

**Comment by cjnolet** [comment]
Linking this to relevant dask-cuda issue: https://github.com/rapidsai/ucx-py/issues/542
