### ISSUE TITLE
[QST] Having trouble using UCX on rapids-dgx202 machine

### ISSUE THREAD

**Issue by think-high** [rapidsai/ucx-py#590]
**What is your question?**
I am trying to run my Cluster on UCX instead of TCP on rapids-dgx202 machine but I am getting some error which I need help with. The code runs fine if I run the cluster without UCX

Here is the snippet I am using to run my cluster:
```
os.environ["DASK_RMM__POOL_SIZE"] = "1GB"
os.environ["DASK_UCX__CUDA_COPY"] = "True"  # os.environ needs using strings, not Python True/False
os.environ["DASK_UCX__TCP"] = "True"
os.environ["DASK_UCX__NVLINK"] = "True"
os.environ["DASK_UCX__INFINIBAND"] = "True"
os.environ["DASK_UCX__NET_DEVICES"] = "enp134s0f1"


from dask.distributed import Client
from dask_cuda import LocalCUDACluster
from dask_cuda.initialize import initialize

cluster = LocalCUDACluster(
    protocol = "ucx",
    interface = "ib0",  # Interface -- used for the scheduler
    enable_tcp_over_ucx = True,
    enable_nvlink = True,
    enable_infiniband = True,
    ucx_net_devices="auto",
    rmm_pool_size="24GB"
)
client = Client(cluster)

client
```

Here is the error: 

`
KilledWorker: ("('clean-getitem-read-csv-head-1-5-getitem-485ace84ee78a375681c07da648b3ef0', 0)", <Worker 'ucx://172.16.8.241:53504', name: 3, memory: 0, processing: 1>)
`
Here is the trace:
<details>

```

distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/dask_cudf_profiling/__init__.py in __init__(self, df, **kwargs)
     67         """Constructor see class documentation
     68         """
---> 69         sample = kwargs.get('sample', df.head())
     70 
     71         #dask_cudf_profiling timing

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
   1004             Whether to compute the result, default is True.
   1005         """
-> 1006         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
   1007 
   1008     def _head(self, n, npartitions, compute, safe):

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/dask/dataframe/core.py in _head(self, n, npartitions, compute, safe)
   1037 
   1038         if compute:
-> 1039             result = result.compute()
   1040         return result
   1041 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    445         postcomputes.append(x.__dask_postcompute__())
    446 
--> 447     results = schedule(dsk, keys, **kwargs)
    448     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    449 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2691                     should_rejoin = False
   2692             try:
-> 2693                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2694             finally:
   2695                 for f in futures.values():

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1988                 direct=direct,
   1989                 local_worker=local_worker,
-> 1990                 asynchronous=asynchronous,
   1991             )
   1992 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    831         else:
    832             return sync(
--> 833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    834             )
    835 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1847                             exc = CancelledError(key)
   1848                         else:
-> 1849                             raise exception.with_traceback(traceback)
   1850                         raise exc
   1851                     if errors == "skip":

KilledWorker: ("('clean-getitem-read-csv-head-1-5-getitem-485ace84ee78a375681c07da648b3ef0', 0)", <Worker 'ucx://172.16.8.241:53504', name: 3, memory: 0, processing: 1>)

```
</details>

**Comment by quasiben** [comment]
What versions of UCX-Py / Dask / cuDF are you using ?  Also, can you first try without InfiniBand turned on?

**Comment by think-high** [comment]
I don't have UCX-Py setup in my env. I will quickly to that. Do you think that could be the reason for InfiniBand?
Here are the versions for dask and cudf:

```
dask                      2.17.2+12.g8eeb0e01          pypi_0    pypi
dask-core                 2.23.0                     py_0
dask-cuda                 0.15.0a200602           py37_12    rapidsai-nightly
dask-cudf                 0.15.0a200604   py37_gaeda0c0_774    rapidsai-nightly

```

**Comment by think-high** [comment]
I am getting the following error with InfiniBand disabled. 

It was not letting me run with ucx_net_devices="auto" so I changed to the specific device. Here is the snippet:

```
cluster = LocalCUDACluster(
    protocol = "ucx",
    interface = "ib0",  # Interface -- used for the scheduler
    enable_tcp_over_ucx = True,
    enable_nvlink = True,
    enable_infiniband = False,
    ucx_net_devices="enp134s0f1",
    rmm_pool_size="24GB"
)
client = Client(cluster)

```
Error:

`OSError: Timed out trying to connect to 'ucx://172.16.8.240:60998' after 10 s: Timed out trying to connect to 'ucx://172.16.8.240:60998' after 10 s: connect() didn't finish in time
`

Trace:
<details>

```
Task exception was never retrieved
future: <Task finished coro=<_listener_handler_coroutine() done, defined at /home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py:144> exception=UCXError('Destination is unreachable')>
Traceback (most recent call last):
  File "/home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py", line 156, in _listener_handler_coroutine
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 387, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 57, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
Task exception was never retrieved
future: <Task finished coro=<_listener_handler_coroutine() done, defined at /home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py:144> exception=UCXError('Destination is unreachable')>
Traceback (most recent call last):
  File "/home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py", line 156, in _listener_handler_coroutine
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 387, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 57, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
Task exception was never retrieved
future: <Task finished coro=<_listener_handler_coroutine() done, defined at /home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py:144> exception=UCXError('Destination is unreachable')>
Traceback (most recent call last):
  File "/home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py", line 156, in _listener_handler_coroutine
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 387, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 57, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
Task exception was never retrieved
future: <Task finished coro=<_listener_handler_coroutine() done, defined at /home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py:144> exception=UCXError('Destination is unreachable')>
Traceback (most recent call last):
  File "/home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py", line 156, in _listener_handler_coroutine
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 387, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 57, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
Task exception was never retrieved
future: <Task finished coro=<_listener_handler_coroutine() done, defined at /home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py:144> exception=UCXError('Destination is unreachable')>
Traceback (most recent call last):
  File "/home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py", line 156, in _listener_handler_coroutine
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 387, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 57, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
Task exception was never retrieved
future: <Task finished coro=<_listener_handler_coroutine() done, defined at /home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py:144> exception=UCXError('Destination is unreachable')>
Traceback (most recent call last):
  File "/home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py", line 156, in _listener_handler_coroutine
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 387, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 57, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
Task exception was never retrieved
future: <Task finished coro=<_listener_handler_coroutine() done, defined at /home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py:144> exception=UCXError('Destination is unreachable')>
Traceback (most recent call last):
  File "/home/u00u54en00lSx138Oa357/anaconda3/envs/rapids-env/lib/python3.7/site-packages/ucp/core.py", line 156, in _listener_handler_coroutine
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 387, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 57, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Destination is unreachable
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/comm/core.py in connect(addr, timeout, deserialize, handshake_overrides, **connection_args)
    312             if not comm:
--> 313                 _raise(error)
    314         except FatalCommClosedError:

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/comm/core.py in _raise(error)
    265         )
--> 266         raise IOError(msg)
    267 

OSError: Timed out trying to connect to 'ucx://172.16.8.240:60998' after 10 s: connect() didn't finish in time

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-5-1a5045a72918> in <module>
     23     enable_infiniband = False,
     24     ucx_net_devices="enp134s0f1",
---> 25     rmm_pool_size="24GB"
     26 )
     27 client = Client(cluster)

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/dask_cuda/local_cuda_cluster.py in __init__(self, n_workers, threads_per_worker, processes, memory_limit, device_memory_limit, CUDA_VISIBLE_DEVICES, data, local_directory, protocol, enable_tcp_over_ucx, enable_infiniband, enable_nvlink, enable_rdmacm, ucx_net_devices, rmm_pool_size, rmm_managed_memory, **kwargs)
    249                 )
    250             },
--> 251             **kwargs,
    252         )
    253 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/deploy/local.py in __init__(self, n_workers, threads_per_worker, processes, loop, start, host, ip, scheduler_port, silence_logs, dashboard_address, worker_dashboard_address, diagnostics_port, services, worker_services, service_kwargs, asynchronous, security, protocol, blocked_handlers, interface, worker_class, scheduler_kwargs, **worker_kwargs)
    234             asynchronous=asynchronous,
    235             silence_logs=silence_logs,
--> 236             security=security,
    237         )
    238 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/deploy/spec.py in __init__(self, workers, scheduler, worker, asynchronous, loop, security, silence_logs, name)
    274         if not self.asynchronous:
    275             self._loop_runner.start()
--> 276             self.sync(self._start)
    277             self.sync(self._correct_state)
    278 

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    169             return future
    170         else:
--> 171             return sync(self.loop, func, *args, **kwargs)
    172 
    173     async def _get_logs(self, scheduler=True, workers=True):

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/deploy/spec.py in _start(self)
    307             connection_args=self.security.get_connection_args("client"),
    308         )
--> 309         await super()._start()
    310 
    311     def _correct_state(self):

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/deploy/cluster.py in _start(self)
     62 
     63     async def _start(self):
---> 64         comm = await self.scheduler_comm.live_comm()
     65         await comm.write({"op": "subscribe_worker_status"})
     66         self.scheduler_info = await comm.read()

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/core.py in live_comm(self)
    770                 self.timeout,
    771                 deserialize=self.deserialize,
--> 772                 **self.connection_args,
    773             )
    774             comm.name = "rpc"

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/comm/core.py in connect(addr, timeout, deserialize, handshake_overrides, **connection_args)
    323                 backoff = min(backoff, 1)  # wait at most one second
    324             else:
--> 325                 _raise(error)
    326         else:
    327             break

~/anaconda3/envs/rapids-env/lib/python3.7/site-packages/distributed/comm/core.py in _raise(error)
    264             error,
    265         )
--> 266         raise IOError(msg)
    267 
    268     backoff = 0.01

OSError: Timed out trying to connect to 'ucx://172.16.8.240:60998' after 10 s: Timed out trying to connect to 'ucx://172.16.8.240:60998' after 10 s: connect() didn't finish in time
```

</details>

**Comment by quasiben** [comment]
You have UCX-Py installed.  It is imported as `ucp`.  Can you try building a new environment and trying again:

> conda create -n 20200825 -c rapidsai-nightly -c nvidia -c conda-forge cudf=0.15 dask-cudf jupyter  ucx-proc=*=gpu ucx ucx-py cudatoolkit=XXXXX

**Comment by VibhuJawa** [comment]
Based on some triaging today with @think-high , this was indeed environment-related and seemed to be working now. 

@think-high , Can you confirm and close/update this issue accordingly? 


Thanks all for the help.

**Comment by pentschev** [comment]
I'd like only to remind you all that IB in RAPLAB is unstable and should be avoided.
