### ISSUE TITLE
RMM's Out of Memory error on local-send-recv.py benchmark

### ISSUE THREAD

**Issue by benjha** [rapidsai/ucx-py#625]
After running some intra node benchmarks in batch mode on Summit for UCX-Py 0.16

https://github.com/rapidsai/ucx-py/issues/616#issuecomment-701063608
https://github.com/rapidsai/ucx-py/issues/616#issuecomment-701486255

RMM outputs the next error

```
MESSAGE SIZE:  100MB
Server Running at 10.41.21.51:59058
Client connecting to server at 10.41.21.51:59058
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/gpfs/alpine/world-shared/stf011/benjha/ucx/ucx-py/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/gpfs/alpine/world-shared/stf011/benjha/ucx/ucx-py/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/alpine/stf011/world-shared/benjha/ucx/ucx/ucx-py/benchmarks/local-send-recv.py", line 55, in server
    devices=[args.server_dev],
  File "/gpfs/alpine/world-shared/stf011/benjha/ucx/ucx-py/lib/python3.7/site-packages/rmm/rmm.py", line 77, in reinitialize
    log_file_name=log_file_name,
  File "rmm/_lib/memory_resource.pyx", line 305, in rmm._lib.memory_resource._initialize
  File "rmm/_lib/memory_resource.pyx", line 365, in rmm._lib.memory_resource._initialize
  File "rmm/_lib/memory_resource.pyx", line 64, in rmm._lib.memory_resource.PoolMemoryResource.__cinit__
MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp:68: cudaErrorMemoryAllocation out of memory
[1601483081.517894] [e37n08:44770:0]         parser.c:1600 UCX  WARN  unused env variable: UCX_TCP_TX_SEG_SIZE,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
Roundtrip benchmark
--------------------------
n_iter      | 10
n_bytes     | 100.00 MB
object      | rmm
reuse alloc | True
==========================
Device(s)   | 0, 1
Average     | 9.63 GB/s
--------------------------
Iterations
--------------------------
000         |  8.06 GB/s
001         | 10.45 GB/s
002         |  9.68 GB/s
003         |  9.82 GB/s
004         |  9.84 GB/s
005         |  9.84 GB/s
006         |  9.83 GB/s
007         |  9.84 GB/s
008         |  9.84 GB/s
009         |  9.55 GB/s
[1601483085.514269] [e37n08:44827:0]         parser.c:1600 UCX  WARN  unused env variable: UCX_TCP_TX_SEG_SIZE,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
[1601483081.517761] [e37n08:44769:0]         parser.c:1600 UCX  WARN  unused env variable: UCX_TCP_TX_SEG_SIZE,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
[e37n08:44769:0:44769] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[e37n08:44769:0:44769] ib_mlx5_log.c:139  RC QP 0xc134 wqe[43]: SEND --e [inl len 69]
```

UCX's env. variables used to run `local-send-recv.py` are 
```
export UCX_RNDV_SCHEME='get_zcopy'
export UCX_NET_DEVICES='mlx5_0:1,mlx5_3:1'
export UCX_MAX_RNDV_RAILS=2
export UCX_TLS='rc_x,sm,cuda_copy,cuda_ipc,gdr_copy'
export UCX_RNDV_THRESH=1 
```
and

```
export UCX_RNDV_SCHEME='get_zcopy'
export UCX_NET_DEVICES='mlx5_0:1,mlx5_3:1'
export UCX_MAX_RNDV_RAILS=2
export UCX_TLS='rc_x,sm,cuda_copy'
export UCX_RNDV_THRESH=1
unset UCX_MEM_MMAP_HOOK_MODE
```

while the call to `local-send-recv.py` is

```
jsrun --nrs 1 --tasks_per_rs 2 --cpu_per_rs 2 --gpu_per_rs 2 --rs_per_host 1  --latency_priority CPU-CPU --launch_distribution packed --bind packed:1 python local-send-recv.py --server-dev 0 --client-dev 1 --object_type rmm --reuse-alloc --n-bytes $MSG_SIZE --port 12345
```

<details><summary>Conda Environment</summary>
<p>

```
 conda list           
# packages in environment at /gpfs/alpine/world-shared/stf011/benjha/ucx/ucx-py:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bokeh                     2.2.1            py37hc8dfbb8_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cmake-setuptools          0.1.3                    pypi_0    pypi
cupy                      7.5.0                    pypi_0    pypi
cython                    0.29.20          py37he6710b0_0  
cytoolz                   0.10.1           py37h6eb9509_0    conda-forge
dask                      2.19.0                     py_0    conda-forge
dask-core                 2.19.0                     py_0    conda-forge
distributed               2.19.0           py37hc8dfbb8_0    conda-forge
freetype                  2.10.2               h33812df_0    conda-forge
fsspec                    0.8.3                      py_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       67.1                 hb209c28_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-ppc64le     2.33.1               h0f24833_7  
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 8.2.0                h822a55f_1  
libgfortran-ng            8.4.0               h822a55f_16    conda-forge
libhwloc                  2.1.0                h130b219_0    conda-forge
libiconv                  1.15              h6eb9509_1006    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                ha38281c_6    conda-forge
libpng                    1.6.37               h151fe60_1    conda-forge
libstdcxx-ng              8.2.0                h822a55f_1  
libtiff                   4.1.0                hee46ee4_6    conda-forge
libwebp-base              1.1.0                h6eb9509_3    conda-forge
libxml2                   2.9.10               h5e8a603_1    conda-forge
llvmlite                  0.32.1           py37hd408876_0  
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                hb209c28_1    conda-forge
markupsafe                1.1.1            py37h2bd1440_1    conda-forge
msgpack-python            1.0.0            py37h70ed317_1    conda-forge
ncurses                   6.2                  he6710b0_1  
numba                     0.49.0           py37h0573a6f_0  
numpy                     1.19.2                   pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h6eb9509_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.3            py37he1dd5e6_1    conda-forge
partd                     1.1.0                      py_0    conda-forge
pillow                    7.1.2            py37h83d961d_0    conda-forge
pip                       20.2.2                   py37_0  
psutil                    5.7.2                    pypi_0    pypi
pynvml                    8.0.4                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.7.9                h3a5dbe6_0  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py37h2bd1440_0    conda-forge
readline                  8.0                  h7b6447c_0  
rmm                       0.16.0                   pypi_0    pypi
setuptools                49.6.0                   py37_1  
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
spdlog                    1.8.0                hfd86e86_1  
sqlite                    3.33.0               hbc83047_0  
tbb                       2020.1               h1bb5118_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py37h2bd1440_1    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
ucx-py                    0.16.0a0+177.g1de1344          pypi_0    pypi
wheel                     0.35.1                     py_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.4                h6eb9509_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.4                h1dc757f_3    conda-forge
```

</p>
</details>

**Comment by benjha** [comment]
by using `--tasks_per_rs 1`  instead of `--tasks_per_rs 2` the error disappears.

**Comment by pentschev** [comment]
That makes sense, this was probably because you then had two processes competing for a GPU's memory. Thanks for testing that @benjha .

**Comment by jakirkham** [comment]
Have you tried overriding the initial pool size? It may be we just need a larger pool to start. Mentioning this as we have encountered similar issues before.

**Comment by jakirkham** [comment]
Also issue ( https://github.com/rapidsai/ucx-py/issues/578 ) may be relevant.
