### ISSUE TITLE
Handle empty cuda arrays

### ISSUE THREAD

**Issue by TomAugspurger** [rapidsai/ucx-py#70]
Right now, we don't handle empty cuda arrays well.

Numba represents these as an object whose data field is `(None, _)`.

```python
In [1]: import numba.cuda

In [2]: arr = numba.cuda.device_array(0)

In [3]: arr.__cuda_array_interface__
Out[3]:
{'shape': (0,),
 'strides': (8,),
 'data': (None, False),
 'typestr': '<f8',
 'version': 0}
```

cupy represents them with a `(0, _)`:

```
In [4]: import copy
In [8]: arr = cupy.random.random(0)

In [9]: arr.__cuda_array_interface__
Out[9]:
{'shape': (0,),
 'typestr': '<f8',
 'descr': [('', '<f8')],
 'data': (0, False),
 'version': 0}
```

I know that we fail immediately on the first case.

```pytb
distributed.core - ERROR - an integer is required
Traceback (most recent call last):
  File "/home/nfs/an.taugspurger/ucx-dev-env/distributed/distributed/core.py", line 361, in handle_comm
    result = yield result
  File "/home/nfs/an.taugspurger/miniconda3/envs/ucx-dev-test/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/nfs/an.taugspurger/miniconda3/envs/ucx-dev-test/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/nfs/an.taugspurger/ucx-dev-env/distributed/distributed/worker.py", line 952, in get_data
    compressed = yield comm.write(msg, serializers=serializers)
  File "/home/nfs/an.taugspurger/miniconda3/envs/ucx-dev-test/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/nfs/an.taugspurger/ucx-dev-env/distributed/distributed/comm/ucx.py", line 150, in write
    await self.ep.send_obj(frame)
  File "ucp_py/_libs/ucp_py.pyx", line 323, in ucp_py.ucp_py_ep.send_obj
  File "ucp_py/_libs/ucp_py.pyx", line 299, in ucp_py.ucp_py_ep._send_obj_cuda
  File "ucp_py/_libs/ucp_py_buffer_helper.pyx", line 217, in ucp_py.buffer_region.populate_cuda_ptr
TypeError: an integer is required
```

Not sure about the second one

**Comment by quasiben** [comment]
resolved by #137

**Comment by jakirkham** [comment]
Guessing this should have been closed. Feel free to reopen if not. 🙂

**Comment by quasiben** [comment]
yes, thank you @jakirkham
